### ISSUE TITLE
Improvements for the event system

### ISSUE THREAD

**Issue by marco-a** [florian/x18n#10]
I have a few points for improvements here:

**- Language change event:**

- I would only fire it when the language really has been changed: changing the language from `en` to `en` should not fire an unnecessary language change event.
- Providing the old and new set locale as arguments can be useful in some cases: `on('lang:change', function (oldLocale, newLocale) {})`.

**- Dictionary change event:**
- Passing the locale in what the dictionary was changed in can be useful too: `on('dict:change', function (inWhatLocale) { })`.

**Comment by florian** [comment]
Everything implemented in v2 :+1:
