### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by pvnr0082t** [florian/x18n#14]
Hi @florian ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host this project in cdnjs.
I'm not sure if `x18n_build.js` need to be added in cdnjs. Could you please help me?
Thank you.

https://github.com/cdnjs/cdnjs/issues/8011

**Comment by florian** [comment]
x18n_build.js is x18n bundled with all dependencies.
The x18n.js file is for NPM (or other package managers) which loads all dependencies.

So for cdnjs hosting x18n_build.js seems like the correct choice. :)

**Comment by pvnr0082t** [comment]
Thank you!! @florian :+1:
