### ISSUE TITLE
IE8 problem

### ISSUE THREAD

**Issue by perghosh** [florian/x18n#6]
In IE8 (and probably in earlier versions of IE) there is a bug in line ~92. Code looks like:

    fn.apply(null, args);

If `args` is undefined or null in IE8 it doesn't work.

I changed this to 

        if( args ) { fn.apply(null, args); }
        else { fn.apply(null); }

**Comment by florian** [comment]
Thanks for the bug report!
I fixed this in [Observable v2.0.1](https://github.com/florian/observable/commit/01f8d2c74f8c3f4b56f5ce5282c2cee03faa9881)
